name: Rust

on:
  pull_request:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Run Cargo Login
        run: cargo login ${{ secrets.FANTASY_UTIL_API_KEY }}
      - name: Run Cargo Package
        run: cargo package --all-features
      - name: Run Cargo Publish
        run: cargo publish --all-features
